name: italo
version: 0.11.1.0-1
summary: "ITALO is a revolutionary video platform in which publishers can make money with their content, without ads. https://italo.network"
description: |
    ITALO coin is a digital cryptocurrency. Initially, at the genesis of the ITALO blockchain, the maximum number of coins minable is set to 18 Millions coins.
    Revenues from co-mining are passed on to the viewers and on to the copyright holders as content is consumed on the platform.
grade: devel
confinement: strict

apps:
    italod:
        daemon: forking
        command: |
          italod-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/italod.conf
        plugs:
            - network
            - network-bind
    italo-wallet-rpc:
        command: |
          italo-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    italo-wallet-cli:
        command: |
          italo-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libzmqpp-dev
            - libzmq3-dev
            - libsodium-dev
            - libdb-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - libreadline6-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/italod.conf: etc/italod.conf
            contrib/snap/italod-wrapper: bin/italod-wrapper
        prime:
            - etc
            - bin
